
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yaqueline
 */
public class Actualizar extends javax.swing.JFrame {

    /**
     * Creates new form Actualizar
     */
    private static int orden_tabla;
    private static int cantidad_filas=0;
    private static int fila=0;    
    public Actualizar(int orden) {
        initComponents();        
        orden_tabla=orden;        
    }

    private Actualizar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollPane1 = new java.awt.ScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(482, 452));
        setSize(new java.awt.Dimension(482, 490));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 103, 490, 250));

        jPanel2.setBackground(new java.awt.Color(61, 147, 124));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_update_left_rotation_36px.png"))); // NOI18N
        jLabel1.setText("  Registros de clientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 110));

        jPanel3.setBackground(new java.awt.Color(35, 65, 79));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Actualizar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 490, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setSize(490, 490);
        crearTabla();
        switch (orden_tabla){
            case 0:
                jLabel1.setText("Registros de Clientes");
                break;
            case 1:
                jLabel1.setText("Registros de Ventas");
                break;
            case 2:
                jLabel1.setText("Registros de Productos");
                break;
            case 3:
                jLabel1.setText("Registros de Proveedores");
                break;
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if (fila<=cantidad_filas){
            Object Temp[][]=new Object[100][100];        
            Consultas_SQL c = new Consultas_SQL();                  
            switch (orden_tabla){
                case 0:                
                    Temp = c.Leer_Cliente();       
                    Crear_Cliente V=new Crear_Cliente((String)Temp[fila][0],(String)Temp[fila][1],(String)Temp[fila][2],(int)Temp[fila][3],(int)Temp[fila][4],true,this);
                    V.setVisible(true);
                    V.setDefaultCloseOperation(1);
                    break;
                case 1:                
                    Temp = c.Leer_Venta();                
                    Crear_Venta V2=new Crear_Venta((int)Temp[fila][1],(int)Temp[fila][2],(int)Temp[fila][3],(int)Temp[fila][0],true,this);
                    V2.setVisible(true);
                    V2.setDefaultCloseOperation(1);
                    break;
                case 2:
                    Temp = c.Leer_Producto();                
                    Crear_Producto V3=new Crear_Producto((String)Temp[fila][0],(int)Temp[fila][1],(int)Temp[fila][2],(int)Temp[fila][3],(int)Temp[fila][4],true,this);
                    V3.setVisible(true);
                    V3.setDefaultCloseOperation(1);
                    break;
                default:
                    Temp = c.Leer_Proveedor();   
                    Crear_Proveedor V4=new Crear_Proveedor((String)Temp[fila][1],(String)Temp[fila][2],(String)Temp[fila][3],(String)Temp[fila][4],(String)Temp[fila][5],(int)Temp[fila][0],true,this);
                    V4.setVisible(true);
                    V4.setDefaultCloseOperation(1);
            }     
            c.Desconectar();
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked
public void crearTabla(){
        //Creamos una matriz de objetos donde guardar los datos de la tabla a leer
        Object Temp[][]=new Object[100][100];
        //Llamamos la clase donde estan nuestras consultas
        Consultas_SQL c = new Consultas_SQL();        
        //Añadimos los nombres de las columnas de la tabla
        String[] Columnas_Cliente = {"Nombre","Direccion","Telefono","Descuento","ID Cliente"};                
        String[] Columnas_Venta = {"ID Venta","ID Cliente","ID Producto","Cantidad","Fecha"};        
        String[] Columnas_Producto = {"Tipos","ID Proveedor","Peso","Precio","ID Producto"};        
        String[] Columnas_Proveedor = {"ID Proveedor","Nombre","Telefono","Numero de cuenta","Direccion","Correo Electronico"};            
        //final significa que la variable no va a cambiar, volviendose una constante
        final JTable tabla;
        //Dependiendo del numero de orden de la tabla a leer llamamos la consulta de nuestra clase
        switch (orden_tabla){
            case 0:                
                Temp = c.Leer_Cliente();        
                //Le asignamos los datos y los nombres de las columnas a la tabla dependiendo de cada caso
                tabla=new JTable(Temp,Columnas_Cliente);
                break;
            case 1:                
                Temp = c.Leer_Venta();
                tabla=new JTable(Temp,Columnas_Venta);
                break;
            case 2:
                Temp = c.Leer_Producto();
                tabla=new JTable(Temp,Columnas_Producto);
                break;
            default:
                Temp = c.Leer_Proveedor();
                tabla=new JTable(Temp,Columnas_Proveedor);
        }                  
        c.Desconectar();
        cantidad_filas=c.Obt_cantidad_filas();
        JScrollPane scroll=new JScrollPane(tabla);
        scroll.setBounds(4,242,425,100);
        scrollPane1.add(scroll);
        scroll.setVisible(true);
        tabla.addMouseListener(new MouseAdapter()
        {
            @Override
            public void mouseClicked(MouseEvent e)
            {
                fila = tabla.rowAtPoint(e.getPoint());                
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
